id = "phpactor"
name = "PHP Phpactor"
description = "PHP support and Phpactor LSP"
version = "0.0.1"
schema_version = 1
authors = ["Xander <1174877+xtrasmal@users.noreply.github.com>"]
repository = "https://github.com/xtrasmal/zed-lsp-phpactor"

[language_servers.phpactor]
name = "Phpactor"
language = "PHP"
language_ids = { PHP = "php" }

[grammars.php]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "8ab93274065cbaf529ea15c24360cfa3348ec9e4"
path = "php"
